template_controller:
    name: Template controller
    description: Actions from template controller
    parent: root
    class: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    method: templateAction
