js:
  - '@OroUIBundle/Resources/public/lib/base64.js'
  - '@OroUIBundle/Resources/public/lib/underscore.js'
  - '@OroUIBundle/Resources/public/lib/backbone.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.mousewheel.min.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.numeric.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.uniform.min.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap.min.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap-tooltip.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap-popover.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap.switch.js'

  - '@OroUIBundle/Resources/public/js/layout.js'
  - '@OroUIBundle/Resources/public/js/csrf.js'
  - '@OroUIBundle/Resources/public/js/backbone/app.js'
  - '@OroUIBundle/Resources/public/js/backbone/app/model.js'
  - '@OroUIBundle/Resources/public/js/backbone/app/view.js'
  - '@OroUIBundle/Resources/public/js/backbone/app/router.js'
  - '@OroUIBundle/Resources/public/js/backbone/app/collection.js'
  - '@OroUIBundle/Resources/public/js/backbone/setup.js'

  - '@FOSJsRoutingBundle/Resources/public/js/router.js'

  - '@OroUIBundle/Resources/public/js/backbone/app/events.js'

  - '@OroUIBundle/Resources/public/js/jquery.form.js'
  - '@OroUIBundle/Resources/public/js/hash.navigation.js'
  - '@OroUIBundle/Resources/public/js/url.min.js'

  - '@FOSJsRoutingBundle/Resources/public/js/router.js'