parameters:
    oro_dataaudit.log_datagrid.manager.class: Oro\Bundle\DataAuditBundle\Datagrid\LogDatagridManager

services:
    oro_dataaudit.log_datagrid.manager:
        class: %oro_dataaudit.log_datagrid.manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: log
              entity_name: Oro\Bundle\DataAuditBundle\Entity\Log
              entity_hint: log
              route_name: oro_dataaudit_index
        calls:
            - [ setRouter, [ @router ] ]
