parameters:
    oro_dataaudit.datagrid.manager.class:       Oro\Bundle\DataAuditBundle\Datagrid\AuditDatagridManager

services:
    oro_dataaudit.datagrid.manager:
        class:                                  %oro_dataaudit.datagrid.manager.class%
        tags:
            - name:                             oro_grid.datagrid.manager
              datagrid_name:                    audit
              entity_name:                      Oro\Bundle\DataAuditBundle\Entity\Audit
              entity_hint:                      audit
              route_name:                       oro_dataaudit_index
              query_entity_alias:               a
