parameters:
    oro_user.user_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\UserDatagridManager
    oro_user.role_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\RoleDatagridManager
    oro_user.group_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\GroupDatagridManager
    oro_user.user_datagrid_manager_light.class: Oro\Bundle\UserBundle\Datagrid\LightUserDatagridManager

services:
    oro_user.user_datagrid_manager:
        class: %oro_user.user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Oro\Bundle\UserBundle\Entity\User
              entity_hint: users
              flexible: true
              route_name: oro_user_index
        calls:
            - [ setRouter, [ @router ] ]

    oro_user.role_datagrid_manager:
        class: %oro_user.role_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: roles
              entity_name: Oro\Bundle\UserBundle\Entity\Role
              entity_hint: roles
              route_name: oro_user_role_index
        calls:
            - [ setRouter, [ @router ] ]

    oro_user.group_datagrid_manager:
        class: %oro_user.group_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: groups
              entity_name: Oro\Bundle\UserBundle\Entity\Group
              entity_hint: groups
              route_name: oro_user_group_index
        calls:
            - [ setRouter, [ @router ] ]

    oro_user.role_user_datagrid_manager:
        class: %oro_user.user_datagrid_manager_light.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: roleusers
              entity_hint: user
              route_name: oro_user_role_user_grid
        calls:
            - [ setRouter, [ @router ] ]

    oro_user.group_user_datagrid_manager:
        class: %oro_user.user_datagrid_manager_light.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: groupusers
              entity_hint: user
              route_name: oro_user_group_user_grid
        calls:
            - [ setRouter, [ @router ] ]