parameters:
    oro_user.user_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\UserDatagridManager
    oro_user.role_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\RoleDatagridManager
    oro_user.group_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\GroupDatagridManager

services:
    oro_user.user_datagrid_manager:
        class: %oro_user.user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Oro\Bundle\UserBundle\Entity\User
              entity_hint: users
              flexible: true
              route_name: oro_user_index

    oro_user.role_datagrid_manager:
        class: %oro_user.role_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: roles
              entity_name: Oro\Bundle\UserBundle\Entity\Role
              entity_hint: roles
              route_name: oro_user_role_index

    oro_user.group_datagrid_manager:
        class: %oro_user.group_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: groups
              entity_name: Oro\Bundle\UserBundle\Entity\Group
              entity_hint: groups
              route_name: oro_user_group_index
