parameters:
    oro_search.datagrid.all_results.class:       Oro\Bundle\SearchBundle\Datagrid\AllResultsDatagrid
    oro_search.datagrid.all_results.pager.class: Oro\Bundle\SearchBundle\Datagrid\AllResultsPager

    oro_search.datagrid.all_results.name:  "oro_search_results_all"

services:
    oro_search.datagrid.all_results.route_generator:
        class: %oro_grid.route.default_generator.class%
        arguments:
            - @router
            - %oro_search.datagrid.all_results.name%

    oro_search.datagrid.all_results.parameters:
        class: %oro_grid.datagrid.parameters.class%
        arguments:
            - @service_container
            - "oro_search_results"

    oro_search.datagrid.all_results.pager:
        class: %oro_search.datagrid.all_results.pager.class%

    oro_search.datagrid.all_results:
        class: %oro_search.datagrid.all_results.class%
        arguments:
            - @form.factory
            - @translator
            - @oro_search.index
            - @oro_search.datagrid.all_results.route_generator
            - @oro_search.datagrid.all_results.parameters
            - %oro_search.datagrid.all_results.name%
            - "results"
