parameters:
    oro_search.datagrid_results.datagrid_manager.class: Oro\Bundle\SearchBundle\Datagrid\SearchDatagridManager
    oro_search.datagrid_results.datagrid_builder.class: Oro\Bundle\SearchBundle\Datagrid\SearchDatagridBuilder
    oro_search.datagrid_results.query_factory.class:    Oro\Bundle\SearchBundle\Datagrid\IndexerQueryFactory

services:
    oro_search.datagrid_results.datagrid_manager:
        class: %oro_search.datagrid_results.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: oro_search_results
              entity_hint: results
              route_name: oro_search_results
              query_factory: oro_search.datagrid_results.query_factory
              datagrid_builder: oro_search.datagrid_results.datagrid_builder

    oro_search.datagrid_results.query_factory:
        class: %oro_search.datagrid_results.query_factory.class%
        arguments:
            - @oro_search.index

    oro_search.datagrid_results.datagrid_builder:
        class: %oro_search.datagrid_results.datagrid_builder.class%
        arguments:
            - @form.factory
            - @oro_grid.filter.factory
            - @oro_grid.sorter.factory
            - @oro_grid.action.factory
            - %oro_grid.datagrid.class%


