attributes_config:
    Text:
        backend:
            type:          string
        frontend:
            field_type:    text
            field_options: ~
    Email:
        backend:
            type:          string
        frontend:
            field_type:    email
            field_options: ~
    Url:
        backend:
            type:          string
        frontend:
            field_type:    url
            field_options: ~
    Money:
        backend:
            type:          decimal
        frontend:
            field_type:    money
            field_options: ~
    Metric:
        backend:
            type:          decimal
        frontend:
            field_type:    number
            field_options: ~
    TextArea:
        backend:
            type:          text
        frontend:
            field_type:    textarea
            field_options: ~
    Date:
        backend:
            type:          text
        frontend:
            field_type:    textarea
            field_options: ~
    SimpleChoice:
        backend:
            type:          options
        frontend:
            field_type:    choice
            field_options: ~
    MultipleChoice:
        backend:
            type:          options
        frontend:
            field_type:    choice
            field_options: {multiple: true}

