entities_config:
    Oro\Bundle\UserBundle\Entity\User:
        flexible_manager:     oro_user.manager
        flexible_class:       Oro\Bundle\UserBundle\Entity\User
        flexible_value_class: Oro\Bundle\UserBundle\Entity\UserValue
