entities_config:
    Oro\Bundle\UserBundle\Entity\User:
        flexible_manager:            oro_user.flexible_manager
        flexible_entity_class:       Oro\Bundle\UserBundle\Entity\User
        flexible_entity_value_class: Oro\Bundle\UserBundle\Entity\UserValue