attributes_config:
    Text:
        backend:
            type:          varchar
        frontend:
            field_type:    text
            field_options: ~
    Email:
        backend:
            type:          varchar
        frontend:
            field_type:    email
            field_options: ~
    Url:
        backend:
            type:          varchar
        frontend:
            field_type:    url
            field_options: ~
    Money:
        backend:
            type:          decimal
        frontend:
            field_type:    money
            field_options: ~
    Number:
        backend:
            type:          decimal
        frontend:
            field_type:    number
            field_options: ~
    Integer:
        backend:
            type:          integer
        frontend:
            field_type:    integer
            field_options: ~
    Metric:
        backend:
            type:          decimal
        frontend:
            field_type:    number
            field_options: ~
    TextArea:
        backend:
            type:          text
        frontend:
            field_type:    textarea
            field_options: ~
    Date:
        backend:
            type:          date
        frontend:
            field_type:    textarea
            field_options: ~
    DateTime:
        backend:
            type:          datetime
        frontend:
            field_type:    textarea
            field_options: ~
    SimpleChoice:
        backend:
            type:          options
        frontend:
            field_type:    choice
            field_options: {multiple: false, expanded: true}
    MultipleChoice:
        backend:
            type:          options
        frontend:
            field_type:    choice
            field_options: {multiple: true, expanded: true}

