services:
    oro_grid.form.type.date_range:
        class:     Oro\Bundle\GridBundle\Form\Type\DateRangeType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_date_range }

    oro_grid.form.type.datetime_range:
        class:     Oro\Bundle\GridBundle\Form\Type\DateTimeRangeType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_datetime_range }

    oro_grid.form.filter.type.number:
        class:     Oro\Bundle\GridBundle\Form\Type\Filter\NumberType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_filter_number }

    oro_grid.form.filter.type.choice:
        class:     Oro\Bundle\GridBundle\Form\Type\Filter\ChoiceType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_filter_choice }

    oro_grid.form.filter.type.date_range:
        class:     Oro\Bundle\GridBundle\Form\Type\Filter\DateRangeType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_filter_date_range }

    oro_grid.form.filter.type.datetime_range:
        class:     Oro\Bundle\GridBundle\Form\Type\Filter\DateTimeRangeType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_filter_datetime_range }

    oro_grid.form.filter.type.flexible_options:
        class:     Oro\Bundle\GridBundle\Form\Type\Filter\Flexible\OptionsType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_grid_type_filter_flexible_options }
