oro_menu_config:
    templates:
        navbar:
            template: 'OroNavigationBundle:Menu:navbar.html.twig'
        dropdown:
            template: 'OroNavigationBundle:Menu:dropdown.html.twig'
        horizontal_tabs:
            template: 'OroNavigationBundle:Menu:horizontal_tabs.html.twig'
        pinbar:
            template: 'OroNavigationBundle:Menu:pinbar.html.twig'
        favorite:
            template: 'OroNavigationBundle:Menu:favorites.html.twig'
        history:
            template: 'OroNavigationBundle:Menu:menu.html.twig'
            rootClass: 'extra-list'
