oro_menu_config:
    templates:
        application_menu:
            template: 'OroUIBundle:Menu:application_menu.html.twig'
        shortcuts:
            template: 'OroUIBundle:Menu:shortcuts.html.twig'

    items:
        home:
            name: 'Home'
            label: ''
            extras:
                icon: 'icon-home icon-white'
            uri: '#'

    tree:
        application_menu:
            type: application_menu
            children:
                home: ~

        shortcuts:
            type: shortcuts