oro_menu_config:
    items:
        system_tab:
            label: 'System'
            uri: '#'
        user_list:
            label: 'Users'
            route: 'oro_user_index'
            extras:
                routes: ['/^oro_user_(?!role\w+|group\w+)\w+$/']
        user_roles:
            label: 'Roles'
            route: 'oro_user_role_index'
            extras:
                routes: ['oro_user_role_*']
        user_groups:
            label: 'Groups'
            route: 'oro_user_group_index'
            extras:
                routes: ['oro_user_group_*']
        shortcut_new_user:
            label: Create New User
            route: oro_user_create
            extras:
                description: Create new user instance
                isCustomAction: true
        shortcut_list_users:
            label: Users List
            route: oro_user_index
            extras:
                description: List of users
                isCustomAction: true

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        user_list: ~
                        user_roles: ~
                        user_groups: ~

        shortcuts:
            children:
                shortcut_new_user: ~
                shortcut_list_users: ~

oro_titles:
    oro_user_show: %%username%% - View profile - User Management
    oro_user_edit: %%username%% - Edit profile - User Management
    oro_user_create: New profile - User Management
    oro_user_index: Users - User Management

    oro_user_role_edit: Edit role - User management
    oro_user_role_create: Add role - User management
    oro_user_role_index: "Roles - User management"

    oro_user_security_login: Login
    oro_user_status_list: "User Statuses - User Management"
    oro_user_status_create: "Add Status - User Management"

    oro_user_reset_reset: Password Reset
    oro_user_reset_request: Forgot Password
    oro_user_reset_check_email: Password Reset - Check Email

    oro_user_acl_edit: Acl Resources - User Management

    oro_user_group_create: Add group - User Management
    oro_user_group_edit: Edit group - User Management
    oro_user_group_index: Groups - User Management
