oro_menu_config:
    items:
        audit_tab:
            label: 'Data Audit'
            uri: '#'
        audit_list:
            label: 'Grid'
            route: 'oro_dataaudit_index'

    tree:
        application_menu:
            children:
                audit_tab:
                    children:
                        audit_list: ~
