oro_menu_config:
    templates:
        navbar:
            template: 'OroNavigationBundle:Menu:navbar.html.twig'
        dropdown:
            template: 'OroNavigationBundle:Menu:dropdown.html.twig'
        horizontal_tabs:
            template: 'OroNavigationBundle:Menu:horizontal_tabs.html.twig'
        pinbar:
            template: 'OroNavigationBundle:Menu:pinbar.html.twig'
        favorite:
            template: 'OroNavigationBundle:Menu:favorites.html.twig'
        history:
            template: 'OroNavigationBundle:Menu:history.html.twig'
            rootClass: 'extra-list'
            currentAsLink: false

oro_titles:
    oro_user_show: "%%user%% - Profile"
    oro_user_role_index: "Roles"
    oro_user_role_edit: "Edit %%role%% role"
