services:
    oro_grid.orm.filter.type.boolean:
        class: Oro\Bundle\GridBundle\Filter\ORM\BooleanFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_boolean }

    oro_grid.orm.filter.type.callback:
        class: Oro\Bundle\GridBundle\Filter\ORM\CallbackFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_callback }

    oro_grid.orm.filter.type.choice:
        class: Oro\Bundle\GridBundle\Filter\ORM\ChoiceFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_choice }

    oro_grid.orm.filter.type.date_range:
        class: Oro\Bundle\GridBundle\Filter\ORM\DateRangeFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_date_range }

    oro_grid.orm.filter.type.datetime_range:
        class: Oro\Bundle\GridBundle\Filter\ORM\DateTimeRangeFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_datetime_range }

    oro_grid.orm.filter.type.number:
        class:     Oro\Bundle\GridBundle\Filter\ORM\NumberFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_number }

    oro_grid.orm.filter.type.string:
        class:     Oro\Bundle\GridBundle\Filter\ORM\StringFilter
        arguments: ["@translator"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_string }

    oro_grid.orm.filter.type.flexible_string:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleStringFilter
        arguments: ["@service_container"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_string }

    oro_grid.orm.filter.type.flexible_options:
        class:     Oro\Bundle\GridBundle\Filter\ORM\Flexible\FlexibleOptionsFilter
        arguments: ["@service_container"]
        tags:
            - { name: oro_grid.filter.type, alias: oro_grid_orm_flexible_options }
