oro_dataaudit_bundle:
    resource:     "@OroDataAuditBundle/Controller"
    type:         annotation
    prefix:       /audit

oro_dataaudit_api_history:
    resource:     "@OroDataAuditBundle/Controller/Api/Rest/LogController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest
