oro_search_api:
    resource: Oro\Bundle\SearchBundle\Controller\Api\SearchController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
    defaults:
        version: latest

oro_search_soap_api:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   api/soap/