oro_windows_index:
    pattern: /
    defaults: { _controller: FrameworkBundle:Template:template, template: "OroWindowsBundle:Default:windowsPage.html.twig" }

oro_windows:
    resource: "@OroWindowsBundle/Controller/"
    type:     annotation

oro_windows_api:
    resource: Oro\Bundle\WindowsBundle\Controller\Api\WindowsStateController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
    defaults:
        version: latest
