oro_address_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\AddressController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
    defaults:
        version: latest

oro_countries_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\CountryController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
    defaults:
        version: latest