oro_user_bundle:
    resource:     "@OroUserBundle/Controller"
    type:         annotation
    prefix:       /user

oro_user_api:
    resource:     "@OroUserBundle/Controller/Api/Rest/UserController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest