parameters:
    oro_dataflow.connectors.class: Oro\Bundle\DataFlowBundle\DependencyInjection\Chain\ConnectorChain

services:
    oro_dataflow.connectors:
        class: "%oro_dataflow.connectors.class%"
