###
# Main search service
##
services:
    oro_search.index:
        class:        Oro\Bundle\SearchBundle\Engine\Indexer
        arguments:    ["@doctrine.orm.entity_manager", "@oro_search.search.engine", "@translator", %oro_search.entities_config%]

    oro_search.index_listener:
        class:        Oro\Bundle\SearchBundle\EventListener\IndexListener
        arguments:    ["@service_container", %oro_search.entities_config%]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }


    oro_search.twig.search_extension:
        class:        Oro\Bundle\SearchBundle\Twig\HighlightExtension
        tags:
            - { name: twig.extension }

    oro_search.result.subscriber:
        class:        Oro\Bundle\SearchBundle\Query\Result\Subscriber\PaginateResultSubscriber
        tags:
            - { name: knp_paginator.subscriber }
