parameters:
#    oro_address.example.class: Oro\Bundle\AddressBundle\Example

services:
#    oro_address.example:
#        class: %oro_address.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
