parameters:
    flexible_manager_class:     Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    user_manager_class:         Oro\Bundle\UserBundle\Entity\UserManager
    user_entity_class:          Oro\Bundle\UserBundle\Entity\User
    user_value_class:           Oro\Bundle\UserBundle\Entity\UserValue
    user_form_class:            Oro\Bundle\UserBundle\Form\Type\UserType
    user_form_subscriber_class: Oro\Bundle\UserBundle\Form\EventListener\FlexibleSubscriber
    user_acl_reader_class:      Oro\Bundle\UserBundle\ResourceReader\Reader
    user_acl_pointcut_class:    Oro\Bundle\UserBundle\Aop\AclPointcut
    user_acl_interceptor_class: Oro\Bundle\UserBundle\Aop\AclInterceptor
    user_acl_manager_class:     Oro\Bundle\UserBundle\Aop\Manager

services:
    oro_user.flexible_manager:
        class:                  %flexible_manager_class%
        arguments:              ["@service_container", %user_entity_class%]

    oro_user.user_manager:
        class:                  %user_manager_class%
        arguments:              ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %fos_user.model.user.class%]

    oro_user.user_provider:
        class:                  Oro\Bundle\UserBundle\Security\UserProvider
        public:                 false
        arguments:              ["@oro_user.user_manager"]

    oro_user.user_form:
        class:                  %user_form_class%
        arguments:              [%user_entity_class%, %user_value_class%]
        tags:
            - { name: form.type, alias: oro_user_form }

    oro_user.user_form_listener:
        class:                  %user_form_subscriber_class%
        arguments:              ["@form.factory", "@oro_user.flexible_manager"]

    oro_user.acl_reader:
        class:                  %user_acl_reader_class%
        arguments:              ["@service_container"]

    oro_user.acl_pointcut:
        class:                  %user_acl_pointcut_class%
        arguments:              [@annotation_reader, @logger]
        tags:
            - { name: jms_aop.pointcut, interceptor: oro_user.acl_interceptor }

    oro_user.acl_interceptor:
        class:                  %user_acl_interceptor_class%
        arguments:              [@security.context, @logger, @service_container]

    oro_user.acl_manager:
        class:                  %user_acl_manager_class%
        arguments:              [@service_container]
