parameters:
    oro_flexibleentity.flexible_config: ~

services:

    # deal with translatable behavior
    oro_flexibleentity.translatable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\Listener\TranslatableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with translatable behavior
    oro_flexibleentity.scopable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\Listener\ScopableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with timestampable behavior
    oro_flexibleentity.timestampable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\Listener\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber }

    # deal with has value required behavior
    oro_flexibleentity.has_required_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\Listener\HasRequiredValueListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with has default value behavior
    oro_flexibleentity.has_default_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\Listener\HasDefaultValueListener
        tags:
            - { name: doctrine.event_subscriber }

    # aims to generate flexible form
    #    oro_flexibleentity.flexible_form_listener:
    #        class: Oro\Bundle\UserBundle\Form\EventListener\FlexibleSubscriber
    #        arguments: ["@form.factory"]

