parameters:
    oro_flexibleentity.flexible_config: ~
    oro_flexibleentity.flexible_config: ~
    oro_flexibleentity.registry.class:  Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManagerRegistry;

services:

    # manager registry
    oro_flexibleentity.registry:
        class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManagerRegistry

    # deal with translatable behavior
    oro_flexibleentity.translatable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\TranslatableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with translatable behavior
    oro_flexibleentity.scopable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\ScopableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with timestampable behavior
    oro_flexibleentity.timestampable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber }

    # deal with required value behavior
    oro_flexibleentity.has_required_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\RequiredValueListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with default value behavior
    oro_flexibleentity.listener.default_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\DefaultValueListener

    # deal with flexible values initialization mode
    oro_flexibleentity.listener.initialize_values_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\InitializeValuesListener
        tags:
            - { name: kernel.event_subscriber}

