parameters:
    oro_user.manager.class:           Oro\Bundle\UserBundle\Entity\UserManager
    oro_user.manager.flexible.class:  Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_user.status.manager.class:    Oro\Bundle\UserBundle\Entity\Manager\StatusManager
    oro_user.entity.class:            Oro\Bundle\UserBundle\Entity\User
    oro_user.entity.value.class:      Oro\Bundle\UserBundle\Entity\UserValue
    oro_user.security.provider.class: Oro\Bundle\UserBundle\Security\UserProvider
    oro_user.security.login.class:    Oro\Bundle\UserBundle\EventListener\LoginSubscriber
    oro_user.type.profile.class:      Oro\Bundle\UserBundle\Form\Type\ProfileType
    oro_user.type.profile.api.class:  Oro\Bundle\UserBundle\Form\Type\ProfileApiType
    oro_user.type.reset.class:        Oro\Bundle\UserBundle\Form\Type\ResetType
    oro_user.type.role.class:         Oro\Bundle\UserBundle\Form\Type\RoleType
    oro_user.type.role.api.class:     Oro\Bundle\UserBundle\Form\Type\RoleApiType
    oro_user.type.group.class:        Oro\Bundle\UserBundle\Form\Type\GroupType
    oro_user.type.group.api.class:    Oro\Bundle\UserBundle\Form\Type\GroupApiType
    oro_user.type.status.class:       Oro\Bundle\UserBundle\Form\Type\StatusType
    oro_user.handler.profile.class:   Oro\Bundle\UserBundle\Form\Handler\ProfileHandler
    oro_user.handler.reset.class:     Oro\Bundle\UserBundle\Form\Handler\ResetHandler
    oro_user.handler.role.class:      Oro\Bundle\UserBundle\Form\Handler\RoleHandler
    oro_user.handler.group.class:     Oro\Bundle\UserBundle\Form\Handler\GroupHandler
    oro_user.handler.status.class:    Oro\Bundle\UserBundle\Form\Handler\StatusHandler
    oro_user.acl.reader.class:        Oro\Bundle\UserBundle\Acl\ResourceReader\Reader
    oro_user.acl.config_reader.class: Oro\Bundle\UserBundle\Acl\ResourceReader\ConfigReader
    oro_user.acl.pointcut.class:      Oro\Bundle\UserBundle\Acl\AclPointcut
    oro_user.acl.interceptor.class:   Oro\Bundle\UserBundle\Acl\AclInterceptor
    oro_user.acl.manager.class:       Oro\Bundle\UserBundle\Acl\Manager
    oro_user.acl.twig.class:          Oro\Bundle\UserBundle\Twig\OroUserExtension
    oro_user.user_menu.builder.class: Oro\Bundle\UserBundle\Menu\UserMenuBuilder
    oro_user.role.listener.class:     Oro\Bundle\UserBundle\EventListener\RoleListener
    oro_user.localized_date.class:    Oro\Bundle\UserBundle\Form\Type\LocalizedDateType
    oro_user.role.manager.class:      Oro\Bundle\UserBundle\Entity\Manager\RoleManager
    oro_user.group.manager.class:     Oro\Bundle\UserBundle\Entity\Manager\GroupManager

services:
    oro_user.manager.flexible:
        class:                        "%oro_user.manager.flexible.class%"
        arguments:                    [%oro_user.entity.class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher"]
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_user.entity.class%}

    oro_user.manager:
        class:                        %oro_user.manager.class%
        arguments:                    [%oro_user.entity.class%, "@doctrine.orm.entity_manager", "@oro_user.manager.flexible", "@security.encoder_factory"]

    oro_user.security.provider:
        class:                        %oro_user.security.provider.class%
        public:                       false
        arguments:                    ["@oro_user.manager"]

    oro_user.security.login:
        class:                        %oro_user.security.login.class%
        arguments:                    ["@oro_user.manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    oro_user.form.profile:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_profile_form", "oro_user_profile", null]

    oro_user.form.profile.api:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["profile", "profile", null]

    oro_user.form.role:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_role_form", "oro_user_role"]

    oro_user.form.role.api:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["role", "role", null]

    oro_user.form.group:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_group_form", "oro_user_group"]

    oro_user.form.group.api:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["group", "group", null]

    oro_user.form.reset:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_reset_form", "oro_user_reset", null, { validation_groups: [ResetPassword, Default] }]

    oro_user.form.type.profile:
        class:                        %oro_user.type.profile.class%
        arguments:                    [%oro_user.entity.class%, %oro_user.entity.value.class%, "@oro_user.acl_manager", "@security.context"]
        tags:
            - { name: form.type, alias: oro_user_profile }

    oro_user.form.type.profile.api:
        class:                        %oro_user.type.profile.api.class%
        arguments:                    [%oro_user.entity.class%, %oro_user.entity.value.class%, "@oro_user.acl_manager", "@security.context"]
        tags:
            - { name: form.type, alias: profile }

    oro_user.form.type.role:
        class:                        %oro_user.type.role.class%
        tags:
            - { name: form.type, alias: oro_user_role }

    oro_user.form.type.role.api:
        class:                        %oro_user.type.role.api.class%
        tags:
            - { name: form.type, alias: role }

    oro_user.form.type.group:
        class:                        %oro_user.type.group.class%
        tags:
            - { name: form.type, alias: oro_user_group }

    oro_user.form.type.group.api:
        class:                        %oro_user.type.group.api.class%
        tags:
            - { name: form.type, alias: group }

    oro_user.form.type.reset:
        class:                        %oro_user.type.reset.class%
        arguments:                    [%oro_user.entity.class%]
        tags:
            - { name: form.type, alias: oro_user_reset }

    oro_user.form.handler.profile:
        class:                        %oro_user.handler.profile.class%
        scope:                        request
        arguments:                    ["@oro_user.form.profile", "@request", "@oro_user.manager"]

    oro_user.form.handler.profile.api:
        class:                        %oro_user.handler.profile.class%
        scope:                        request
        arguments:                    ["@oro_user.form.profile.api", "@request", "@oro_user.manager"]

    oro_user.form.handler.role:
        class:                        %oro_user.handler.role.class%
        scope:                        request
        arguments:                    ["@oro_user.form.role", "@request", "@doctrine.orm.entity_manager"]

    oro_user.form.handler.role.api:
        class:                        %oro_user.handler.role.class%
        scope:                        request
        arguments:                    ["@oro_user.form.role.api", "@request", "@doctrine.orm.entity_manager"]

    oro_user.form.handler.group:
        class:                        %oro_user.handler.group.class%
        scope:                        request
        arguments:                    ["@oro_user.form.group", "@request", "@doctrine.orm.entity_manager"]

    oro_user.form.handler.group.api:
        class:                        %oro_user.handler.group.class%
        scope:                        request
        arguments:                    ["@oro_user.form.group.api", "@request", "@doctrine.orm.entity_manager"]

    oro_user.form.handler.reset:
        class:                        %oro_user.handler.reset.class%
        scope:                        request
        arguments:                    ["@oro_user.form.reset", "@request", "@oro_user.manager"]

    oro_user.acl_reader:
        class:                        %oro_user.acl.reader.class%
        arguments:                    ["@kernel", "@annotation_reader"]

    oro_user.acl_config_reader:
        class:                        %oro_user.acl.config_reader.class%
        arguments:                    ["%kernel.bundles%"]

    oro_user.acl_pointcut:
        class:                        %oro_user.acl.pointcut.class%
        arguments:                    ["@annotation_reader", "@logger"]
        tags:
            - { name: jms_aop.pointcut, interceptor: oro_user.acl_interceptor }

    oro_user.acl_interceptor:
        class:                        %oro_user.acl.interceptor.class%
        arguments:                    ["@service_container"]

    oro_user.acl_manager:
        class:                        %oro_user.acl.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager", "@oro_user.acl_reader", "@cache", "@security.context", "@oro_user.acl_config_reader"]

    oro_user.user_menu:
        class:                        %oro_user.user_menu.builder.class%
        arguments:
            - @security.context
        tags:
            - { name: oro_menu.builder, alias: usermenu }

    oro_user.role.listener:
        class:                        %oro_user.role.listener.class%
        arguments:                    ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    oro_user.twig.user_extension:
        class:                        %oro_user.acl.twig.class%
        arguments:                    ["@oro_user.acl_manager"]
        tags:
            - { name: twig.extension }

    oro_user.form.type.status:
        class:                        %oro_user.type.status.class%
        tags:
            - { name: form.type, alias: oro_user_status }

    oro_user.form.status:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_status_form", "oro_user_status", null]

    oro_user.form.handler.status:
        class:                        %oro_user.handler.status.class%
        scope:                        request
        arguments:                    ["@oro_user.form.status", "@request", "@doctrine.orm.entity_manager", "@oro_user.manager"]

    oro_user.status_manager:
        class:                        %oro_user.status.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager", "@oro_user.manager"]

    oro_user.type.localized_date:
        class:                        %oro_user.localized_date.class%
        tags:
            - { name: form.type, alias: oro_localized_date }

    oro_user.role_manager:
        class:                        %oro_user.role.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_user.group_manager:
        class:                        %oro_user.group.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]
