###
# Main search service
##
services:
    oro_search.index:
        class: Oro\Bundle\SearchBundle\Engine\Indexer
        arguments: [@doctrine.orm.entity_manager, @oro_search.search.engine, %oro_search.entities_config%]