parameters:
    flexible_manager_class:     Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
    user_manager_class:         Oro\Bundle\UserBundle\Entity\UserManager
    user_entity_class:          Oro\Bundle\UserBundle\Entity\User
    user_form_class:            Oro\Bundle\UserBundle\Form\Type\UserType
    user_form_subscriber_class: Oro\Bundle\UserBundle\Form\EventListener\FlexibleSubscriber

services:
    oro_user.flexible_manager:
        class:                  %flexible_manager_class%
        arguments:              ["@service_container", %user_entity_class%]

    oro_user.user_manager:
        class:                  %user_manager_class%
        arguments:              ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %fos_user.model.user.class%]

    oro_user.user_provider:
        class:                  Oro\Bundle\UserBundle\Security\UserProvider
        public:                 false
        arguments:              ["@oro_user.user_manager"]

    oro_user.user_form:
        class:                  %user_form_class%
        arguments:              ["@oro_user.user_form_listener"]
        tags:
            - { name: form.type, alias: oro_user_form }

    oro_user.user_form_listener:
        class:                  %user_form_subscriber_class%
        arguments:              ["@form.factory", "@oro_user.flexible_manager"]