parameters:
    oro_jsfv.event_listener.load_constraints_listener.class: Oro\Bundle\JsFormValidationBundle\EventListener\LoadConstraintsListener

services:
    oro_jsfv.event_listener.load_constraints_listener:
        class: %oro_jsfv.event_listener.load_constraints_listener.class%
        tags:
            - { name: kernel.event_listener, event: jsfv.pre_process, method: onJsfvPreProcess, priority: 255 }
