###
# Main search service
##
services:
    besimple.soap.definition.loader.yml_file:
        class: Oro\Bundle\SearchBundle\ServiceDefinition\Loader\YmlAnnotationClassLoader
        arguments: [@file_locator, @annotation_reader]
        public: false
        tags:
          - { name: besimple.soap.definition.loader }

    oro_search.index:
        class:        Oro\Bundle\SearchBundle\Engine\Indexer
        arguments:    ["@doctrine.orm.entity_manager", "@oro_search.search.engine", %oro_search.entities_config%]

    oro_search.index_listener:
        class:        Oro\Bundle\SearchBundle\EventListener\IndexListener
        arguments:    ["@service_container", %oro_search.entities_config%]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }