parameters:
    oro_address.address.manager.class: Oro\Bundle\AddressBundle\Entity\Manager\AddressManager
    oro_address.address.entity.class: Oro\Bundle\AddressBundle\Entity\Address
    oro_address.address.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_address.address.entity.value.class: Oro\Bundle\AddressBundle\Entity\Value\AddressValue

services:
    oro_address.address.manager.flexible:
        class: %oro_address.address.manager.flexible.class%
        arguments:
            - %oro_address.address.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_address.address.entity.class%}

    oro_address.address.manager:
        class: %oro_address.address.manager.class%
        arguments:
            - %oro_address.address.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_address.address.manager.flexible
