parameters:
    oro_soap.request.class:           Oro\Bundle\SoapBundle\Entity\RequestFix
    oro_soap.loader_yml.class:        Oro\Bundle\SoapBundle\ServiceDefinition\Loader\YmlAnnotationClassLoader

services:
    oro_soap.request:
        class:                        %oro_soap.request.class%
        scope:                        request
        arguments:                    ["@request", "@doctrine.orm.entity_manager"]

    besimple.soap.definition.loader.yml_file:
        class:                        %oro_soap.loader_yml.class%
        arguments:                    ["@file_locator", "@annotation_reader"]
        public:                       false
        tags:
          - { name: besimple.soap.definition.loader }
