parameters:
    oro_grid.datagrid.class:                 Oro\Bundle\GridBundle\Datagrid\Datagrid
    oro_grid.datagrid_manager.class:         Oro\Bundle\GridBundle\Datagrid\DatagridManager
    oro_grid.datagrid.parameters.class:      Oro\Bundle\GridBundle\Datagrid\RequestParameters

    oro_grid.orm.query_factory.entity.class: Oro\Bundle\GridBundle\Datagrid\ORM\QueryFactory\EntityQueryFactory
    oro_grid.orm.query_factory.query.class:  Oro\Bundle\GridBundle\Datagrid\ORM\QueryFactory\QueryFactory

    oro_grid.builder.datagrid.class:         Oro\Bundle\GridBundle\Builder\ORM\DatagridBuilder
    oro_grid.builder.list.class:             Oro\Bundle\GridBundle\Builder\ORM\ListBuilder

    oro_grid.filter.factory.class:           Oro\Bundle\GridBundle\Filter\FilterFactory

    oro_grid.sorter.factory.class:           Oro\Bundle\GridBundle\Sorter\SorterFactory

services:
    oro_grid.datagrid.parameters:
        class:     %oro_grid.datagrid.parameters.class%
        arguments: ["@service_container"]

    oro_grid.builder.datagrid:
        class:     %oro_grid.builder.datagrid.class%
        arguments: ["@form.factory", "@oro_grid.filter.factory", "@oro_grid.sorter.factory"]

    oro_grid.builder.list:
        class:     %oro_grid.builder.list.class%

    oro_grid.filter.factory:
        class:     %oro_grid.filter.factory.class%
        arguments: ["@service_container", ~]

    oro_grid.sorter.factory:
        class:     %oro_grid.sorter.factory.class%
