parameters:
    oro_windows.twig.extension.class: Oro\Bundle\WindowsBundle\Twig\WindowsExtension
    oro_windows.listener.template.class: Oro\Bundle\WindowsBundle\EventListener\TemplateListener

services:
    oro_windows.twig.extension:
        class: %oro_windows.twig.extension.class%
        arguments:
            - @twig
            - @service_container
            - @router
        tags:
            - { name: twig.extension }

    sensio_framework_extra.view.listener:
        class: %oro_windows.listener.template.class%
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
