parameters:
    oro_dataaudit.log.listener.class: Oro\Bundle\DataAuditBundle\EventListener\LogListener

services:
    oro_dataaudit.log.listener:
        class:                        %oro_dataaudit.log.listener.class%
        arguments:                    ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }