parameters:
    oro_dataflow.connectors.class: Oro\Bundle\DataFlowBundle\DependencyInjection\Compiler\ConnectorRegistry

services:
    oro_dataflow.connectors:
        class: "%oro_dataflow.connectors.class%"
