parameters:
    api.security.authentication.listener.class: Oro\Bundle\NavigationBundle\Security\Firewall\ApiListener
    api.security.authentication.entry_point.class: Oro\Bundle\NavigationBundle\Security\EntryPoint\ApiAuthenticationEntryPoint

    oro_menu.factory.class: Oro\Bundle\NavigationBundle\Menu\AclAwareMenuFactory
    oro_menu.builder_chain.class: Oro\Bundle\NavigationBundle\Provider\BuilderChainProvider
    oro_menu.configuration_builder.class: Oro\Bundle\NavigationBundle\Menu\ConfigurationBuilder
    oro_menu.twig.extension.class: Oro\Bundle\NavigationBundle\Twig\MenuExtension

    oro_navigation.navigation_item_menu.builder.class: Oro\Bundle\NavigationBundle\Menu\NavigationItemBuilder
    oro_navigation.navigation_history_menu.builder.class: Oro\Bundle\NavigationBundle\Menu\NavigationHistoryBuilder
    oro_navigation.navigation_mostviewed_menu.builder.class: Oro\Bundle\NavigationBundle\Menu\NavigationMostviewedBuilder

    oro_navigation.item.builder.pinbar.class: Oro\Bundle\NavigationBundle\Entity\Builder\PinbarTabBuilder
    oro_navigation.item.builder.favorite.class: Oro\Bundle\NavigationBundle\Entity\Builder\NavigationItemBuilder
    oro_navigation.item.builder.history.class: Oro\Bundle\NavigationBundle\Entity\Builder\HistoryItemBuilder
    oro_navigation.item.factory.class: Oro\Bundle\NavigationBundle\Entity\Builder\ItemFactory
    oro_navigation.item.pinbar.post_persist_listener.class: Oro\Bundle\NavigationBundle\Entity\Listener\PinbarPostPersist

    oro_navigation.event.response_history.listener.class: Oro\Bundle\NavigationBundle\Event\ResponseHistoryListener

    oro_navigation.menu.matcher.voter.request: Oro\Bundle\NavigationBundle\Menu\Matcher\Voter\RequestVoter

    oro_navigation.title_service.class:                        Oro\Bundle\NavigationBundle\Provider\TitleService
    oro_navigation.title_service.twig.extension.class:         Oro\Bundle\NavigationBundle\Twig\TitleExtension

    oro_navigation.title_service.annotations_reader.class:     Oro\Bundle\NavigationBundle\Title\TitleReader\AnnotationsReader
    oro_navigation.title_service.config_reader.class:          Oro\Bundle\NavigationBundle\Title\TitleReader\ConfigReader

    oro_navigation.title_service.event.request.listener.class: Oro\Bundle\NavigationBundle\Event\RequestTitleListener
    oro_navigation.translation.extractor.class:                Oro\Bundle\NavigationBundle\Title\TranslationExtractor

services:
    oro_menu.factory:
        class: %oro_menu.factory.class%
        arguments:
            - @router
            - @oro_user.acl_manager
        calls:
            - [ setCache, [ @cache ] ]

    oro_menu.builder_chain:
        class: %oro_menu.builder_chain.class%
        arguments:
            - @oro_menu.factory
            - @event_dispatcher
        tags:
            - { name: knp_menu.provider }

    oro_menu.configuration_builder:
        class: %oro_menu.configuration_builder.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: oro_menu.builder }

    oro_menu.twig.extension:
        class: %oro_menu.twig.extension.class%
        arguments:
            - @knp_menu.helper
            - @oro_menu.builder_chain
            - @service_container
        tags:
            - { name: twig.extension }

    api.security.authentication.listener:
        class: %api.security.authentication.listener.class%
        arguments:
            - @security.context
            - @security.authentication.manager
            - ~
            - ~

    api.security.authentication.entry_point:
        class: %api.security.authentication.entry_point.class%

    oro_navigation.item.builder.pinbar:
        class: %oro_navigation.item.builder.pinbar.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_navigation.item.builder, alias: pinbar }

    oro_navigation.item.builder.favorite:
        class: %oro_navigation.item.builder.favorite.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_navigation.item.builder, alias: favorite }

    oro_navigation.item.builder.history:
        class: %oro_navigation.item.builder.history.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_navigation.item.builder, alias: history }

    oro_navigation.item.builder.mostviewed:
        class: %oro_navigation.item.builder.history.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_navigation.item.builder, alias: mostviewed }

    oro_navigation.item.factory:
        class: %oro_navigation.item.factory.class%

    oro_navigation.item.pinbar.post_persist_listener:
        class: %oro_navigation.item.pinbar.post_persist_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oro_navigation.pinbar_menu.builder:
        class: %oro_navigation.navigation_item_menu.builder.class%
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
            - @oro_navigation.item.factory
        tags:
            - { name: oro_menu.builder, alias: pinbar }

    oro_navigation.favorites_menu.builder:
        class: %oro_navigation.navigation_item_menu.builder.class%
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
            - @oro_navigation.item.factory
        tags:
            - { name: oro_menu.builder, alias: favorite }

    oro_navigation.history_menu.builder:
        class: %oro_navigation.navigation_history_menu.builder.class%
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
            - @oro_navigation.item.factory
        calls:
            - [ setMatcher, [ @knp_menu.matcher ]]
            - [ setOptions, [ @oro_config.user ]]
        tags:
            - { name: oro_menu.builder, alias: history }

    oro_navigation.mostviewed_menu.builder:
        class: %oro_navigation.navigation_mostviewed_menu.builder.class%
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
            - @oro_navigation.item.factory
        calls:
            - [ setOptions, [ @oro_config.user ]]
        tags:
            - { name: oro_menu.builder, alias: mostviewed }

    knp_voter_request:
        class: %oro_navigation.menu.matcher.voter.request%
        tags:
            - { name: knp_menu.voter, request: true }


    kernel.listener.nav_history_response:
        class: %oro_navigation.event.response_history.listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
        arguments:
            - @oro_navigation.item.factory
            - @security.context
            - @doctrine.orm.entity_manager
            - @oro_navigation.title_service


    oro_navigation.title_service:
        class: %oro_navigation.title_service.class%
        arguments:
          - @oro_navigation.title_annotations_reader
          - @oro_navigation.title_config_reader
          - @translator.default
          - @doctrine.orm.entity_manager
          - @serializer

    oro_navigation.title_annotations_reader:
        class:                        %oro_navigation.title_service.annotations_reader.class%
        arguments:                    ["@kernel", "@annotation_reader"]

    oro_navigation.title_config_reader:
        class:                        %oro_navigation.title_service.config_reader.class%
        arguments:                    ["%oro_titles%"]

    oro_navigation.title_service.twig.extension:
        class: %oro_navigation.title_service.twig.extension.class%
        arguments:
            - @oro_navigation.title_service
        tags:
            - { name: twig.extension }

    kernel.listener.title_service.request_listener:
        class: %oro_navigation.title_service.event.request.listener.class%
        tags:
            - { name: kernel.event_listener, priority: -255, event: kernel.request, method: onKernelRequest }
        arguments:
            - @oro_navigation.title_service

    oro_navigation.translation.extractor:
        class: %oro_navigation.translation.extractor.class%
        arguments:
            - @oro_navigation.title_service
        tags:
            - { name: translation.extractor, alias: navigation_translation_extractor }
