parameters:
    oro_flexibleentity.flexible_config: ~

services:

    # deal with translatable behavior
    oro_flexibleentity.translatable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\TranslatableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with translatable behavior
    oro_flexibleentity.scopable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\ScopableListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with timestampable behavior
    oro_flexibleentity.timestampable_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber }

    # deal with has value required behavior
    oro_flexibleentity.has_required_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\HasRequiredValueListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }


    # deal with default value behavior
    oro_flexibleentity.listener.default_value_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\DefaultValueListener

    # deal with flexible values initialization mode
    oro_flexibleentity.listener.initialize_values_listener:
        class: Oro\Bundle\FlexibleEntityBundle\EventListener\InitializeValuesListener
        tags:
            - { name: kernel.event_subscriber}

