Oro\Bundle\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        username:
            - NotBlank:
                groups:   [Registration, Profile]
            - Length:
                min:      3
                max:      255
                groups:   [Registration, Profile]
        email:
            - NotBlank:
                groups:   [Registration, Profile]
            - Length:
                min:      6
                max:      255
                groups:   [Registration, Profile]
            - Email:
                groups:   [Registration, Profile]
        plainPassword:
            - NotBlank:
                groups:   [Registration]
            - Length:
                min:      2
                groups:   [Registration, Profile]

Oro\Bundle\UserBundle\Entity\Role:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: role
    properties:
        role:
            - NotBlank:   ~
            - Length:
                max:      30
            - Regex:      "/^ROLE_[a-zA-Z0-9_]+$/"
        label:
            - Length:
                max:      30

Oro\Bundle\UserBundle\Entity\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank:
                groups:   [Registration]
            - Length:
                max:      30
                groups:   [Registration]