Oro\Bundle\AddressBundle\Entity\Address:
    properties:
        street:
            - NotBlank: ~
            - Length:
                  max: 500

        street2:
            - Length:
                  max: 500

        city:
            - NotBlank: ~
            - Length:
                  max: 255

        state:
            - NotBlank: ~

        postalCode:
            - NotBlank: ~
            - Length:
                  max: 20

        country:
            - NotBlank: ~
