parameters:
  oro_search.engine_orm:
        pdo_mysql: Oro\Bundle\SearchBundle\Engine\Orm\PdoMysql
        pdo_pgsql: Oro\Bundle\SearchBundle\Engine\Orm\PdoPgsql


###
# Add orm engine
##
services:
    oro_search.search.engine:
        class: Oro\Bundle\SearchBundle\Engine\Orm
        arguments: [@doctrine.orm.entity_manager, @service_container, %oro_search.entities_config%]
