_welcome:
    pattern:  /
    defaults: { _controller: OroProductBundle:Product:index }

oro_product:
    resource: "@OroProductBundle/Controller/"
    type:     annotation
    prefix:   /product/

oro_manufacturer:
    resource: "@OroManufacturerBundle/Controller/"
    type:     annotation
    prefix:   /manufacturer/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
