_welcome:
    pattern:  /{_locale}
    defaults: { _controller: OroProductBundle:Product:index, _locale: %locale% }

oro_product:
    resource: "@OroProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/product/

oro_manufacturer:
    resource: "@OroManufacturerBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/manufacturer/

oro_customer:
    resource: "@OroCustomerBundle/Controller/"
    prefix:   /{_locale}/customer/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
