parameters:
    oro_crowdin.adapter.class: Oro\Bundle\CrowdinBundle\Provider\CrowdinAdapter
    oro_crowdin.api_key: a439354d66fc86915ffaf7bd5650aba3
    oro_crowdin.endpoint: http://api.crowdin.net/api

services:
    oro_crowdin.adapter:
        class: %oro_crowdin.adapter.class%
        arguments:
            - %oro_crowdin.api_key%
            - %oro_crowdin.endpoint%
