parameters:
    oro_entity_config.metadata.metadata_factory.class:         Metadata\MetadataFactory
    oro_entity_config.metadata.annotation_driver.class:        Oro\Bundle\EntityConfigBundle\Metadata\Driver\AnnotationDriver
    oro_entity_config.listener.entity_subscriber.class:        Oro\Bundle\EntityConfigBundle\EventListener\DoctrineSubscriber

services:
    oro_entity_config.metadata.annotation_metadata_factory:
        class:                                              %oro_entity_config.metadata.metadata_factory.class%
        arguments:                                          [@oro_entity_config.metadata.annotation_driver]
        public:                                             false

    oro_entity_config.metadata.annotation_driver:
        class:                                              %oro_entity_config.metadata.annotation_driver.class%
        arguments:                                          [@annotation_reader]
        public:                                             false

#    oro_entity_config.listener.entity_subscriber:
#        class: %oro_entity_config.listener.entity_subscriber.class%
#        arguments:
#            - @oro_entity_extend.db_id_name_generator
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
